### ISSUE TITLE
UI & Functionality

### ISSUE THREAD

**Issue by patrickm663** [nickmplay/annuity-app#1]
Hi @nickmplay 

As discussed, happy to assist on the dashboard.

For ease of reference, I am including the UI & functionality tasks here:

- [x]  Incorporate Legend into Sidebar -- Attempt to link the legend with the sidebar in order to list reinsurers with a coloured cell in the second column 
- [x]  Stylise the "ri_winner" text output
- [x]  For the “ri_selection”, make the choices be the subset of unique reinsurers that are listed in the “ri_select” output variable (note not all the reinsurers quote on every deal in the sample data loaded)
- [x]  Alter the size of the two plots so that you don’t need to scroll down to see the second plot

Please let me know if parts were misunderstood or if there is additional functionality we can help with.

Kind regards
Patrick

**Comment by nickmplay** [comment]
Great idea - list looks good. Thanks

**Comment by patrickm663** [comment]
Thanks @nickmplay. Currently 2-4 are complete and in the "1-ui-functionality" branch. The bit of the legend I need to think a bit about and test some things as it requires custom HTML/CSS styling.

I will keep you posted with a PR once the changes are complete for your review.
